### ISSUE TITLE
/usr/lib64/libldb.so.1: undefined reference to `rep_memset_s@LDB_1.5.5'

### ISSUE THREAD

**Issue by undrwater** [rodlie/cyan#73]
Trying to build your new version, and getting the following after:
`make -j4`
`[  2%] Automatic MOC for target Cyan
[  2%] Built target Cyan_autogen
[  5%] Linking CXX executable Cyan
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libldb.so.1: undefined reference to `rep_memset_s@LDB_1.5.5'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/Cyan.dir/build.make:696: Cyan] Error 1
make[1]: *** [CMakeFiles/Makefile2:77: CMakeFiles/Cyan.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

**Comment by rodlie** [comment]
I don't know, probably some depend/linker issue on your system. Cyan builds fine on all the system I test.

CMakeLists.txt uses static link flags as default so that may introduce some issues on some systems(?). You could go through CMakeLists.txt and remove "STATIC" from all lines with "_STATIC" and see if that works better.

**Comment by undrwater** [comment]
Works now without changes to CMakeLists.txt. Not sure if it was something in my system, or an addition to the commit.

Feel free to close this issue, and thank you.
